### ISSUE TITLE
Document File Formats on Wiki

### ISSUE THREAD

**Issue by LordNed** [LordNed/WArchive-Tools#4]
...and remove the few comments from the tools, ie: 
RARC::FileEntry
/// <summary>

Padding byte. Included here for the sake of documentation. </summary>

 // Non actual struct items

etc.

Document the format thoroughly on the wiki, make the code simpler and cleaner.

**Comment by Sage-of-Mirrors** [comment]
I might have a format spec on file that I made when I was writing my archive packer. If I do have one, I'll copy it over.

**Comment by Sage-of-Mirrors** [comment]
I have written and published documentation on all three parts of the archive format (header, node, file entry). If there is anything you'd like to expand upon, feel free to edit the page yourself or ask me.
